### ISSUE TITLE
How to test ISTD dataset with original size

### ISSUE THREAD

**Issue by yx-chan131** [cvlab-stonybrook/SID#13]
Hi, I notice that in infer.py the size of the images are set to 256x256. May I know how can I run inference on image of original size, i.e. 480x680. I tried to uncomment line 38 and line 39 in src/data/single_dataset.py to not resizing them but it didn't work, runtime error shows that  "Sizes of tensors must match except in dimension 2. Got 2 and 3 (The offending index is 0)".

Thanks!

**Comment by hieulem** [comment]
Hi @yx-chan131,

Since we are using U-Net for estimating shadow mattes, the size of the input images has to be multipliers of 256. You can just use the input of size 256x256 to produce the shadow parameters. And then use the input of size 768*768 to produce a high-res matte layer. You then resize the matte layer to the original size of the input and use them to generate the shadow-free image at its original size. 

Please let me know how it goes, I am happy to assist you further if necessary :)
